package io.availe.builders

internal const val TOP_LEVEL_CLASS_KDOC: String =
    "A sealed interface hierarchy representing all versions of the %L data model."
internal const val FILE_HEADER_COMMENT: String = "Generated by KReplica. Do not edit."

internal fun generateVersionBoxKdoc(versionName: String, schemaVersion: Int): String {
    val title = "Version $schemaVersion ($versionName)"
    val line = "--------------------------"
    val content = "|   $title   |"
    return """
        $line
        $content
        $line
    """.trimIndent()
}