package io.availe.builders

internal const val TOP_LEVEL_CLASS_KDOC: String =
    "A sealed interface hierarchy representing all versions of the %L data model."
internal const val SHARED_VALUE_CLASSES_KDOC: String =
    "SHARED VALUE CLASSES\n\nType-safe wrappers for properties that are consistent across versions."
internal const val CONFLICTED_VALUE_CLASSES_KDOC: String =
    "CONFLICTED (VERSION-SPECIFIC) VALUE CLASSES\n\nType-safe wrappers for properties that have different underlying types in different schema versions."
internal const val STANDALONE_VALUE_CLASSES_KDOC: String = "VALUE CLASSES"
internal const val FILE_HEADER_COMMENT: String = "Generated by KReplica. Do not edit."

internal fun generateVersionBoxKdoc(versionName: String, schemaVersion: Int): String {
    val title = "Version $schemaVersion ($versionName)"
    val line = "--------------------------"
    val content = "|   $title   |"
    return """
        $line
        $content
        $line
    """.trimIndent()
}